site_name: My Docs


docs_dir: site
site_dir: public

theme:
  name: material

site_name: Портфолио
site_url: https://ohotoo.github.io/demo72/

plugins:
  - search
  - tags
  - macros

nav:
  - Главная: index.md
  - Навыки: skills.md
  - FAQ: faq.md
  - Проекты: project.md
  - Связь: phone.md

extra:
  nothing: "Здесь ничего нет. ПОка что."